services:
  webserv:
    build:
      context: ../
      dockerfile: example/Dockerfile
    ports:
      - "1998:1998"
    volumes:
      - ./public/cgi:/var/www/html:Z
      - ./config:/etc/webserv:Z
      - ./public/upload:/srv/upload:Z
