#:schema ./config.schema.json

[[server]]
ports = [80]

[[server.route]]
preffix = "/"
path = "/var/www/html"

[[server.route]]
preffix = "/imgs"
path = "/usr/share/pixmaps/"

[[server.api]]
uri = "/api/hello"
external = false
func = "echo"

[[server.cgi]]
glob = "/*.php"
bin = "/usr/bin/php-cgi"
