#:schema ../../docs/config.schema.json

[[server]]
ports = [1998]

[[server.route]]
preffix = "/"
path = "/var/www/html"
index = "index.php"

[[server.route]]
preffix = "/imgs"
path = "/usr"

[[server.api]]
uri = "/api/hello"
external = false
func = "echo"

[[server.api]]
uri = "/api/upload"
external = false
func = "upload"
upload = { path = "/var/tmp", random_len = 32 }

[[server.cgi]]
glob = "/*.php"
bin = "/usr/bin/php-cgi"
