#:schema ../../docs/config.schema.json

[[server]]
port = 6969

[[server.host]]
hostname = "example.com"

[[server.host.route]]
preffix = "/"
path = "/var/www/html"
index = "index.php"

[[server.host.route]]
preffix = "/upload"
path = "/srv/upload"
index = "index.noway"

[[server.host.route]]
preffix = "/imgs"
path = "/usr"

[[server.host.api]]
uri = "/api/upload"
external = false
func = "upload"
upload = { path = "/srv/upload", random_len = 4 }

[[server.host.cgi]]
glob = "/*.php"
bin = "/usr/bin/php-cgi"
