name: CI/CL
on:
  push:
    branches: 
      - main
  pull_request: 
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang make
      
      - name: Building toml98
        run: |
          make -C libs/toml98 all
          make -C libs/toml98 all MODE=release
      
      - name: Running toml98's tests
        run: |
          make -C libs/toml98 test
          ./libs/toml98/tests/toml98_test --verbose

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install Linter Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang clang-tidy make bear

      - name: Generate Compilation Database
        run: |
          # bear captures compiler flags by observing the build process
          bear -- make -C libs/toml98 all

      - name: Register Clang-Tidy Problem Matcher
        run: echo "::add-matcher::.github/clang-tidy-matcher.json"

      - name: Run Clang-Tidy
        run: |
          # Finds all source/header files and runs clang-tidy against them.
          # '-p .' points clang-tidy to the compile_commands.json generated by bear.
          find . -type f \( -name "*.cpp" -o -name "*.hpp" \) ! -path "*/target/*" ! -path "*/tests/*" | xargs -r clang-tidy -p .